### ISSUE TITLE
Error when running `pip install luno_streams`

### ISSUE THREAD

**Issue by Sliqric7053** [jacoduplessis/luno_streams#1]
Hi Jaco

Thank you for your efforts in creating this lib.

When I run `pip install luno_streams` on my Terminal, I get this error:
```
ISLOAN:project-rsithole isloan$ pip install luno_streams
Collecting luno_streams
  Using cached https://files.pythonhosted.org/packages/1d/40/cbb3d44b0211602927502688dcf35970f5fa833f313041da85a6240a9f3b/luno_streams-0.1.2.tar.gz
Collecting websockets (from luno_streams)
  Using cached https://files.pythonhosted.org/packages/4b/c6/026da2eeed75a49dd0b72a0c7ed6ee5cb2943e396ca9753eabff7359b27b/websockets-5.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sn/w6bxj21d72sd7bqrgg5v9wm00000gn/T/pip-build-8nI_4c/websockets/setup.py", line 1, in <module>
        import pathlib
    ImportError: No module named pathlib
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sn/w6bxj21d72sd7bqrgg5v9wm00000gn/T/pip-build-8nI_4c/websockets/
```

Is this a known issue or am I doing something wrong?

Please let me know.

Thanks

Richard

**Comment by jacoduplessis** [comment]
Hi Richard

It seems you have an older version of Python. My library requires Python 3.5 or above. Please check your Python version. 

Regards

Jaco

**Comment by Sliqric7053** [comment]
Cool, I will do so..

Many thanks

**Comment by Sliqric7053** [comment]
Hi Jaco

I've updated to the latest version of python (3.7.1), but I'm still getting the same error.

Please see attached:

![screenshot 2018-11-04 07 41 37](https://user-images.githubusercontent.com/7964516/47960457-4f053600-e005-11e8-82c1-8f708cf296c0.jpg)

Any ideas how I can get this working?

Regards
Richard
