### ISSUE TITLE
Orderbook Lags behind real exchange

### ISSUE THREAD

**Issue by erasmush** [jacoduplessis/luno_streams#5]
Hi Jacques, 

It seems that during times of high volatility the websocket orderbook can lag behind the live exchange. It catches up within 10 seconds or so. I was wondering if you have ever experienced this issue or if there is anything that can be done.

I run my script on a VM with sufficient RAM.

Any advise or direction will be greatly appreciated.

Kind regards
Hannes

**Comment by jacoduplessis** [comment]
Hi Hannes

I don’t use this library at the moment so I can’t comment on the lag. I suspect that comes from Luno’s side. Last time I check they still stated the websocket API is beta. 

Perhaps you can reach out to them to hear what they say about this. If you get any feedback please post it here for others also wondering about this. 

Regards,

Jaco

**Comment by erasmush** [comment]
Apologies, Hi Jaco

Luno has said that the exchange is undergoing changes but they can't give any more detail at this point. Thanks for your feedback.


Kind regards
