### ISSUE TITLE
"luno_streams api_key api_secret pairs [pairs ...]" doesn't work after pip install -e

### ISSUE THREAD

**Issue by zipitup** [jacoduplessis/luno_streams#6]
% pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///usr/home/defaultuser/luno_streams
Requirement already satisfied: websockets in /usr/home/ppp/.local/lib/python3.7/site-packages (from luno-streams==0.1.4) (8.1)
Installing collected packages: luno-streams
  Attempting uninstall: luno-streams
    Found existing installation: luno-streams 0.1.4
    Uninstalling luno-streams-0.1.4:
      Successfully uninstalled luno-streams-0.1.4
  Running setup.py develop for luno-streams
Successfully installed luno-streams

So I did the above, but I can't seem to find the executable "luno_streams" file?

What am I doing wrong?

Thank you.

**Comment by jacoduplessis** [comment]
I would suggest installing the package into a virtual environment and then activating that environment to have access to the luno_streams command.

If you are not familiar with virtual environments, I can suggest some reading to get you started.

**Comment by zipitup** [comment]
Thanks.
